import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/header";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        cz-shortcut-listen="true"
      >
        <main>
        <Header/>
        {children}
        </main>
        <Toaster/>
      </body>
    </html>
  );
}
